behaviors:
  AIDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.5
      gail:
        strength: 0.5
        demo_path: C:\Users\o7\Unity projects\New folder\Kansei\Demos\Track_0.demo
    behavioral_cloning:
      strength: 0.5
      demo_path:  C:\Users\o7\Unity projects\New folder\Kansei\Demos\Track_0.demo
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 64
    summary_freq: 60000

