behaviors:
  AIDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 2.0e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: C:\Users\o7\Unity projects\New folder\Kansei\Demos\SimpleTrackRight.demo
    behavioral_cloning:
      strength: 0.5
      demo_path:  C:\Users\o7\Unity projects\New folder\Kansei\Demos\SimpleTrackRight.demo
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000